name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda

    - name: Initialize Conda
      run: |
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        conda init bash

    - name: Create and Activate Conda Environment
      run: |
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        conda create -q -n myenv python=3.9
        conda activate myenv

    - name: Install Dependencies with Conda
      run: |
        conda activate myenv
        conda install pip
        pip install -r docs/requirements.txt

    - name: Build Sphinx Documentation
      run: |
        conda activate myenv
        cd docs
        make html

    - name: Deploy Sphinx Documentation
      uses: ammaraskar/sphinx-action@master
      with:
        build-command: "echo 'Building already done in previous step'"
        publish-directory: docs/_build/html
        token: ${{ secrets.GITHUB_TOKEN }}
